---

language: python
python: "3.6.9"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix

before_install:
  - sudo apt-get update -qq

install:
  - pip install pelican Markdown typogrify

script:
  # Check the role/playbook's syntax.
  - make html

deploy:
  provider: s3
  # access_key_id: "YOUR AWS ACCESS KEY"
  # secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "	recipe-book-hosting-bitonti"
  skip_cleanup: true
  upload-dir: output
