---

language: python
python: "3.6.9"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix

before_install:
  - sudo apt-get update -qq

install:
  - pip install pelican Markdown typogrify

script:
  - make publish

deploy:
  provider: s3
  # access_key_id: "YOUR AWS ACCESS KEY"
  # secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "web-recipe-book-616655032796"
  skip_cleanup: true
  local-dir: output
  acl: private
  region: eu-west-1
  on:
    branch: master
